<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>
    <p>
        
        <input type="hidden" value="User" name="role" >
    </p>
    <p>
        
        <input type="hidden" value="Restricted" name="status" >
    </p>
    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
        <?php echo $this->tag->linkTo(
    'login',
    'Login Here!'
); ?>
    </p>

</form>