

<?php
if(!$this->session->has('userole')){
  $this->response->redirect('../login/');
}
if ($users->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); echo $this->tag->linkTo('../login/logout','Logout');?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}


?>

<?php
if ($blogs->count()> 0) {
    ?><form method="POST" action="../dashboard/change" >
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>BlogId</th>
            <th>Title</th>
            <th>Details</th>
            
            <th>Status</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Blogs quantity: <?php echo $blogs->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($blogs as $blog) { ?>
            <tr>
                <td><?php echo $blog->blogid; ?></td>
                <td><?php echo $blog->title; ?></td>
                <td><?php echo $blog->details; ?></td>
               
                <td><?php echo $blog->status; ?></td>
                <td><?php //echo $this->tag->submitButton(['Change Status','class' => 'btn btn-warning','value'=> $blog->id ,'name'=>'btnchange']);
                          echo '<button name="btnchange" class="btn btn-Warning" value="'.$blog->id.'" >Change Status</button>' ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table></form>
    <?php
}

